const defaultDatabase = {
    nombre_bd: '',
    descripcion_bd: null,
    categoria_datos: '',
    herramientas_gestion: '',
    calidad_datos: '',
    limpieza_validacion: false,
    descripcion_limpieza_validacion: null,
    proveedores_bd: '',
    ejes_estrategicos: [],
    periodicidad: '',
    descripcion_periodicidad: null,
    tiene_diccionario: false,
    archivo_tiene_diccionario: '',
    objetivos_uso: '',
    usuarios_datos: '',
    quienes_son: '',
    historicos: false,
    descripcion_historicos: null,
    migracion_actualizacion: false,
    descripcion_migracion_actualizacion: null,
    medidas_seguridad: false,
    descripcion_medidas_seguridad: null,
    normativas_proteccion: false,
    descripcion_normativas_proteccion: null,
    plan_contingencia: false,
    descripcion_plan_contingencia: null,
    interoperabilidad: false,
    descripcion_interoperabilidad: null,
    plataformas_difusion: false,
    nombre_plataformas_difusion: '',
    url_plataformas_difusion: '',
};

export default defaultDatabase;